### ISSUE TITLE
在群晖里docker安装成功但邮件通知不行

### ISSUE THREAD

**Issue by harry10086** [idoop/zentao#1]
我安装后发现其他功能都可以，设置邮件时提示无法连接到SMTP服务器，请关闭SELinux什么的。感觉是这个容器无法连接外网。因为对docker不了解，所以不知道怎么操作了。

**Comment by 2751409540** [comment]
遇到同样的问题。
1.把smtp的域名改为ip地址后，可以连接上服务器（虽然后续认证各种出错），表明容器内部的dns设置是存在问题的
2. smtp选择不加密的25号端口，显示错误SMTP -> ERROR: AUTH not accepted from server: 503 5.5.1 Error: authentication not enabled ，同样的smtp配置用outlook发信ok
3. smtp选择ssl 465端口，禅道这边出现 SMTP -> ERROR: Failed to connect to server: (0) 错误，同样的配置outlook正常
4. 另外测试了服务器开放的starttls 587端口，禅道全部失败。

**Comment by 2751409540** [comment]
进一步研究后，已配置成功。
smtp服务器在支持587端口的情况下，貌似禅道配置为该端口会校验ssl证书的合法性且不能跳过，放弃。
smtp服务器在outlook上支持25端口是因为outlook的认证设置为auto，实际上的认证是从25端口切换到tls的587，如果是postfix为邮件服务器需要设置取消tls的强制认证：smtpd_tls_auth_only = no

**Comment by idoop** [comment]
@harry3633 
- 0.群晖默认没有selinux；
- 1.确认群晖是否能连接外网.在群晖控制台打开Docker应用-容器-双击{禅道容器}-终端机-新增，使用命令:`wget smtp.qq.com`查看能否解析出腾讯smtp服务的IP.

@2751409540 当docker使用默认网络类型为`bridge`或者`host`时，继承的是宿主机的网络与DNS，也就是说宿主机能访问到的域名或IP，容器内部同样能访问到，因此先用宿主机ping一下SMTP的地址是否能连通，另外可以看看SMTP是否正确配置。另外由于运行环境是一致的，所以你只需修改挂载出来**/opt/zbox/**中的文件实现自定制。
