### ISSUE TITLE
禅道自动构建失败，禅道的下载地址貌似拦截了curl

### ISSUE THREAD

**Issue by zhangsean** [idoop/zentao#12]
Docker Hub自动构建失败，手工curl -s ${ZENTAO_URL}返回内容是500，你那边有这个问题吗？

**Comment by idoop** [comment]
No, it's all right. I think this is DockerHub autobuild machine's network problem. I've had this problem before, because all autobuild machines is in USA, but Zentao's CDN in China, so sometime the network request will timeout or interrupt. Just retry.

**Comment by zhangsean** [comment]
Thanks.
