### ISSUE TITLE
docker-entrypoint有问题，无法启动

### ISSUE THREAD

**Issue by chengaomin** [idoop/zentao#13]
/usr/local/bin/docker-entrypoint: line 57: [: argument expected

![image](https://user-images.githubusercontent.com/4586906/58383109-12327800-8005-11e9-9648-475b1a05c625.png)

**Comment by idoop** [comment]
Repaired.
If you use *docker-compose*, It is recommended to use `extra_hosts` instead of `SMTP_HOST`.
