### ISSUE TITLE
容器重启后，禅道会自动升级

### ISSUE THREAD

**Issue by goodleo** [idoop/zentao#17]
容器重启后，禅道会自动升级，然后禅道目录就会被删除，禅道就不能访问了

**Comment by idoop** [comment]
你的描述实在是没有任何有帮助的信息，我只能告诫你任何服务升级前请做好相应的备份工作。

**Comment by goodleo** [comment]
![image](https://user-images.githubusercontent.com/7307798/64218382-f12ace80-cef3-11e9-8166-ea6ee712e0c6.png)
你好，上面是我看到的docker的日志，使用docker restart 禅道ID ，重启了两次，目录/data/zbox/app/只剩下adminer  ，htdocs    ，upload这3个目录了，目录zen没有了

**Comment by goodleo** [comment]
这个不是我主动升级的，我重启docker restart 禅道ID，就会自动升级

**Comment by idoop** [comment]
@goodleo 看了下，是禅道官方在版本号文件里多写了英文导致比较出错。你重新创建一个新的禅道容器，然后将其中的`/data/zbox/app/zentao`目录复制过来；最后将`upload`目录覆盖掉`zbox/app/zentao/www/data/`下的，将`my.php`替换掉`zbox/app/zentao/config/my.php`即可。

**Comment by idoop** [comment]
@goodleo 或者直接用最新的`11.6.1`的镜像启动升级即可解决问题。
