### ISSUE TITLE
端口问题docker-compose up无法启动

### ISSUE THREAD

**Issue by myme5261314** [idoop/zentao#2]
按照默认设置，docker-compose up，打开网站点击开原版会出现问题。
需要docker exec进去修改/opt/zbox/app/zentao/config/my.php，将其中3306改为3307。

**Comment by myme5261314** [comment]
build from Dockerfile will solve the problem.
seems 3307 issue is from the docker hub image.

**Comment by idoop** [comment]
thx，这个用的**4.9号**官方发布的`9.8.3`，`my.cnf`里边默认就是`3307`，**4.13号上午10点**官方又发布了一遍9.8.3新的安装包替换了原来的，将`my.cnf`重新改回了`3306`端口，dockerHub已经重新发布了，已经没问题了。
