### ISSUE TITLE
why dockerhub's latest tag  is not 11.5?

### ISSUE THREAD

**Issue by tristan-tsl** [idoop/zentao#22]
if you not , the next docker build will be override,thank you very mush

**Comment by idoop** [comment]
@tristan-tsl 
The version  `11.5.1` already exist, just use command `docker pull idoop/zentao:11.5.1`  to get it ,then use command `docker tag`  to `latest`.

**Comment by tristan-tsl** [comment]
11.5

**Comment by idoop** [comment]
@tristan-tsl Pushed.

**Comment by tristan-tsl** [comment]
thank you very mush
