### ISSUE TITLE
想给容器里的apache开一下ssl，能给个思路吗

### ISSUE THREAD

**Issue by xiaopohair** [idoop/zentao#23]
证书申请完成了，但配置的思路没理清楚，可以给个思路吗，多谢。

**Comment by idoop** [comment]
建议不要改容器中的，因为可能会影响到后续的升级。最方便的就是放个前端的Nginx反向代理，可以和zentao容器绑定启动，然后直接在Nginx上配ssl，最后转发到zentao上。

**Comment by xiaopohair** [comment]
好的，受教了。我原来的思路是想直接覆盖container下的apache的conf，但一直在担心有可能官方的conf改了，而我不知道，造成无法使用。
