### ISSUE TITLE
使用docker升级11.7版本时，由于VERSION文件与docker VER参数不一致造成升级后重启docker网站不能访问的问题

### ISSUE THREAD

**Issue by tanqimin** [idoop/zentao#27]
升级前是运行在Docker环境下的11.6.5版本程序，更新11.7镜像后，发现docker程序目录下VERSION版本为11.7.stable，但docker参数ZENTAO_VER的值为11.7，升级成功后，重启docker，会导致版本再执行一次升级：从11.7.stable升级到11.7，而11.7并不存在，导致禅道网站程序被删除的问题。

我恢复数据后，再次执行升级程序，后关闭容器，把ZENTAO_VER版本改为11.7.stable后，重新启动容器，问题解决。

**Comment by idoop** [comment]
不好意思，升级忘了这个特殊情况，已经修复，重新pull即可。
