### ISSUE TITLE
进入容器后，配置完xdd.conf，手动启动xxd.php后，禅道客户端无法连接

### ISSUE THREAD

**Issue by ericshen90** [idoop/zentao#28]
报错`Status code is 404.`

**Comment by ericshen90** [comment]
`docker-compose up -d`启动后，`docker-compose logs -f`没有看到`Start xxd success`，还请赐教

**Comment by idoop** [comment]
@ericshen90 请贴一下你的配置。试一下默认启动，如果能用，那么就是你的配置问题。

**Comment by ericshen90** [comment]
感谢回复，已通过更新禅道客户端解决。
> 避坑：
- 禅道官网`下载`TAB页置顶文中[禅道手机客户端和桌面客户端](https://www.zentao.net/dynamic/zentao-client-80038.html)客户端[`2.4.1`](http://dl.cnezsoft.com/zentaoclient/2.4.1/zentaoclient.mac.zip)已过期
- 使用禅道官网`下载`TAB页置顶文中[禅道企业版 3.5.1 版本发布，主要兼容开源版 11.7，升级禅道客户端](https://www.zentao.net/download/80189.html)的[`3.0.beta4`](http://dl.cnezsoft.com/zentaoclient/3.0.beta4/zentaoclient.mac64.zip)版本
