### ISSUE TITLE
所有的账户包括admin都无法登录

### ISSUE THREAD

**Issue by chenpfeisoo** [idoop/zentao#29]
禅道所有的账户都无法登录，报错“检查用户名密码是否正确”，但是都没修改过密码，也没有密码过期的提示

**Comment by idoop** [comment]
@chenpfeisoo 是改动了什么情况的下出现的？

**Comment by chenpfeisoo** [comment]
感谢回复，没有修改什么，docker部署的，磁盘空间也有

**Comment by idoop** [comment]
用多久了？如果有暴露3306的数据库端口，连上去看下。

**Comment by chenpfeisoo** [comment]
你好，18年5月份部署，数据库可以连接
版本zentao8.3.1

**Comment by idoop** [comment]
抱歉，我这儿没有提供过8.3.1的开源版禅道容器。

**Comment by chenpfeisoo** [comment]
哦哦，我重置密码了，数据库登录了，但是里面资料都没了，啥问题呢？ 这个版本不是开源的吗？ 如果不是开源的是否是自动删除的资料呢？

**Comment by idoop** [comment]
pro版本是收费版，你贴一下你的配置吧，敏感参数用xxx代替即可。

**Comment by chenpfeisoo** [comment]
抱歉，刚给的信息有误，9.8.3的版本，这个是开源的吗 ？ image ： haha123/zentao ：latest

**Comment by idoop** [comment]
是开源的。
数据库丢了，是两个可能，一个是你就没有把数据库挂载出来，第二个则可能是你把`/opt/zbox/`挂载出来后，有人删了挂载出来的这个文件夹，因此重启容器后它自动初始化了。
最后，如果你改过Dockerfile，自己重新构建了一个。那么我这边也无法提供什么支持了。

**Comment by chenpfeisoo** [comment]
好的，感谢回复，我中间有过移动持久化路径的动作，我试试看能否修复

**Comment by chenpfeisoo** [comment]
找回了 之前移动的持久化文件，问题解决，感谢
