### ISSUE TITLE
Docker中邮件无法发出

### ISSUE THREAD

**Issue by xueyulangren** [idoop/zentao#3]
群晖DS418Play上部署的。
用的是阿里云的企业邮箱，群晖可以发出邮件，但是Docker中无法发出。
SMTP 错误：无法连接到 SMTP 主机，请确认禅道机器：
1. 能ping通smtp服务器。如果不能ping通，请查看网络状态，或查看域名解析是否正确，或联系网管；
2. 使用telnet 命令能够连接到smtp的发信端口;
3. 如果上述步骤都是通的，windows请检查防火墙和杀毒软件设置，linux请关闭selnux或者执行"setsebool httpd_can_sendmail true"允许apache可以发信。
SMTP -> ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)

**Comment by xueyulangren** [comment]
![2222](https://user-images.githubusercontent.com/7297689/40407956-9536f6c0-5e98-11e8-8bfc-bdec79e3023a.png)
![1111](https://user-images.githubusercontent.com/7297689/40407958-9610d57a-5e98-11e8-9224-2cf83054a589.png)

**Comment by xueyulangren** [comment]
配置其他的邮件服务器也不行

**Comment by xueyulangren** [comment]
telnet邮件服务器是有响应的，说明网络没有问题。  
telnet smtp.mxhichina.com 465                               
Trying 42.120.219.29...                                                         
Connected to smtp.mxhichina.com.                                                
Escape character is '^]'.                                                       
Connection closed by foreign host.

**Comment by idoop** [comment]
@xueyulangren 请查看此例: #1

**Comment by xueyulangren** [comment]
非常感谢你的回复，测试的网络都是通的，为什么还是发不出邮件呢。
![3333](https://user-images.githubusercontent.com/7297689/40412032-c30e2b98-5ea4-11e8-9764-5e18b2c7f7f8.png)

**Comment by idoop** [comment]
我刚拉下来试了下，OK的。
![1](https://user-images.githubusercontent.com/1930318/40414924-2e2ff012-5eac-11e8-83b4-c19adc5f7a3e.jpg)
![2](https://user-images.githubusercontent.com/1930318/40414942-3dab3ec0-5eac-11e8-934e-503fed1bb26c.jpg)
@xueyulangren

**Comment by xueyulangren** [comment]
@idoop 我这里可能是什么原因呢？我挨着检查了，没有发现什么配置上的问题，QQ邮箱，阿里云邮箱都试过了，测试发信不成功。

**Comment by xueyulangren** [comment]
修改了hosts文件，把smtp服务器加进去就好了。@idoop

**Comment by xueyulangren** [comment]
![4444](https://user-images.githubusercontent.com/7297689/40431363-dc6969ce-5ed9-11e8-8f19-ed4237f209d2.png)
@idoop 但是现在还有一个问题就是重新启动docker之后，修改的记录都没有了，这个有什么办法处理呢？

**Comment by idoop** [comment]
@xueyulangren 更新了下镜像,加了个  **SMTP_HOST**  环境变量,运行的时候再加个`-e SMTP_HOST="42.120.226.4  smtp.mxhichina.com"`即会自动添加到`/etc/hosts`文件了.

**Comment by xueyulangren** [comment]
![55555](https://user-images.githubusercontent.com/7297689/40462191-730c6fd6-5f41-11e8-9c22-1095c47764e2.png)
看启动日志，还有些问题~

**Comment by idoop** [comment]
@xueyulangren 抱歉，想用`debian:stretch`做基础镜像的，改了也没测试。现在已经改回用`ubuntu:16.04`了,再拉一下。

**Comment by xueyulangren** [comment]
@idoop 这个版本已经OK，谢谢！

**Comment by hailiang-wang** [comment]
无法发送邮件，网络ping通。

tail -f apache_error_log

```
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
[Thu Jul 04 18:14:32.471806 2019] [ssl:warn] [pid 37:tid 140237618345728] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Jul 04 18:14:32.475826 2019] [core:warn] [pid 37:tid 140237618345728] AH00098: pid file /opt/zbox/tmp/apache/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Jul 04 18:14:32.477061 2019] [mpm_event:notice] [pid 37:tid 140237618345728] AH00489: Apache/2.4.25 (Unix) OpenSSL/1.0.1 configured -- resuming normal operations
[Thu Jul 04 18:14:32.477084 2019] [core:notice] [pid 37:tid 140237618345728] AH00094: Command line: '/opt/zbox/run/apache/httpd'
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
/opt/zbox/run/apache/httpd: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_alloc_buffer_alloc_array, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

**Comment by idoop** [comment]
@Samurais 请仔细看Readme，里边已经提了，如果设置**SMTP**服务的话，启动时需要添加指定的host，如果你是`docker run`命令启动，带上参数`--add-host smtp.xxx.com:1.1.1.1`，如果是`docker-compose`启动的话，就添加`extra_hosts`字段，仓库的`docker-compose.yaml`中有示例。

**Comment by hailiang-wang** [comment]
这是我用的docker-compose.yml

```
version: "2"
services:
  zentao:
    image: "idoop/zentao:latest"
    restart: always
    extra_hosts:
     - "smtp.exmail.qq.com:163.177.90.125"
    ports:
     - "8030:80"
    environment:
     - ADMINER_USER=root
     - ADMINER_PASSWD=password
     - BIND_ADDRESS=false
    volumes:
     - $PWD/zentao/data:/opt/zbox
```

在容器内测试网络连通

![image](https://user-images.githubusercontent.com/3538629/60659871-1023ca80-9e89-11e9-9341-ec057e69e5dd.png)

**Comment by idoop** [comment]
@Samurais 这些错误不用管，如果smtp设置要加密的话，腾讯邮箱的ssl端口是465，腾讯邮箱smtp没有tls加密，不要选错，我这测试是OK的。
