### ISSUE TITLE
README.md 中tag说明不符

### ISSUE THREAD

**Issue by hxdnshx** [idoop/zentao#31]
在markdown中描述的包含的tag：
``` markdown
**Open soure edition**

- `11.7`,`latest`
- `11.6.1`,`11.6.5`
- `11.3`,`11.4.1`,`11.5.1`,`11.6`
- `10.0`,`10.1`,`10.3`,`10.4`,`10.5`,`10.6`
- `9.6.3`,`9.7`,`9.8`,`9.8.3`
```

实际并没有包含 `10.6` 的Tag
![image](https://user-images.githubusercontent.com/7135944/74811127-d7f3ce00-532b-11ea-9310-207a918013af.png)

**Comment by idoop** [comment]
@hxdnshx  `10.6` 的 tag 打错成`9.6`了，如果要用`10.6`的镜像，你可以直接拉取`9.6`的镜像。
