### ISSUE TITLE
Tag 11.7 missing

### ISSUE THREAD

**Issue by hostSugar** [idoop/zentao#33]
After version 12 was uploaded to hub. Tag 11.7 can not be found.
I want use this feature that updated on 11.7.
Besides i'm worried that version 12 won't be stable,so i need 11.7.

![image](https://user-images.githubusercontent.com/3805562/76067590-9bca9980-5fca-11ea-9cd9-210dc0e65530.png)

**Comment by idoop** [comment]
`11.7` pushed.
