### ISSUE TITLE
有业务数据9.8.1升级到12.0.1报错 Uncaught Error: Call to a member function query() 

### ISSUE THREAD

**Issue by hostSugar** [idoop/zentao#34]
### 有业务数据9.8.1升级到12.0.1，访问 ip:port/zentao/upgrade.php 报错

> 22:48:59 Uncaught Error: Call to a member function query() on null in /opt/zbox/app/zentao/lib/base/dao/dao.class.php:703
> Stack trace:
> #0 /opt/zbox/app/zentao/lib/base/dao/dao.class.php(831): baseDAO->query('SELECT * FROM `...')
> #1 /opt/zbox/app/zentao/module/setting/model.php(39): baseDAO->fetchAll('id')
> #2 /opt/zbox/app/zentao/tmp/model/common.php(43): settingModel->getItems('owner=system&mo...')
> #3 /opt/zbox/app/zentao/module/common/model.php(29): extcommonModel->loadConfigFromDB()
> #4 /opt/zbox/app/zentao/framework/base/router.class.php(1186): commonModel->__construct()
> #5 /opt/zbox/app/zentao/www/upgrade.php(50): baseRouter->loadCommon()
> #6 {main}
> thrown in /opt/zbox/app/zentao/lib/base/dao/dao.class.php on line 703 when visiting

## 详细步骤
18年下载的镜像 `Tag 9.8.1`（目前已不在docker hub中），外部挂载目录 `/opt/cxweb/zentao-9.8.1`，一直作为小组内部项目使用。由于旧服务器资源有限，迁移到了新服务器B。

迁移步骤如下：
1.  `Tag 9.8.1`  生成的容器 78bd26319f1a  制作成镜像
`docker commit 78bd26319f1a idoop/zentao-bak:9.8.1`

2. 导出镜像 `idoop/zentao-bak:9.8.1`
`docker save -o zentao-bak-9.8.1-images.tar idoop/zentao-bak:9.8.1`

3. 导出整个项目文件
`tar -zcvf zentao-981-bak.tar.gz /opt/cxweb/zentao-9.8.1/`

4. scp 复制镜像和项目文件到新服务器B

5. 导入镜像
`docker load < zentao-bak-9.8.1-images.tar`

6. 解压项目文件到 /home/user2
`tar -xvf zentao-981-bak.tar.gz` 
`mv /home/user2/zentao-9.8.1 /home/user2/zbox`

7. 生成9.8.1的容器 zentao-server
> docker run -d -p 19999:80 \
>         -e ADMINER_USER="admin" -e ADMINER_PASSWD="123456" \
>         -e BIND_ADDRESS="false" \
>         -v /home/user2/zbox:/opt/zbox/ \
>         --add-host smtp.exmail.qq.com:113.96.232.106 \
>         --name zentao-server \
>         idoop/zentao-bak:9.8.1

8. **ip:prot/zentao 能正常访问，原有的业务数据都在**

9. 开始升级 12.0.1，停止容器 zentao-server
`docker stop zentao-server && docker rename zentao-server zentao-server-bak`

10. 生成12.0.1的新容器 zentao-server
> docker run -d -p 19999:80 \
>         -e ADMINER_USER="admin" -e ADMINER_PASSWD="123456" \
>         -e BIND_ADDRESS="false" \
>         -v /home/user2/zbox:/opt/zbox/ \
>         --add-host smtp.exmail.qq.com:113.96.232.106 \
>         --name zentao-server \
>         idoop/zentao:12.0.1

11. 升级到12.0.1 日志
> The Zentao need update.
>   Old version: 9.8.1 
>   New version: 12.0.1
> Backuping config / my.php / upload ...
> Upgrading...
> Restoring config / my.php / upload ...
> Upgraded Zentao version to: 12.0.1\nPlease visit your Zentao website to complete the upgrade task.
> Adding password for user admin
> ZBOX是Apache、Mysql、PHP的精简的集成环境。使用时，需要将其解压到/opt目录。
> 
> /opt/zbox/zbox -h     可以获取帮助
> /opt/zbox/zbox start  启动脚本
> 
> Mysql 用户名root，密码为123456。
> 
> 更多可以访问http://www.zentao.net/goto.php?item=zbox.
> Start Apache success
> Start Mysql success
> --2020-03-09 14:17:32--  http://localhost/
> Resolving localhost (localhost)... 127.0.0.1, ::1
> Connecting to localhost (localhost)|127.0.0.1|:80... connected.

12. 访问 `ip:port/zentao/upgrade.php` 报错出现如上一开始的错误
Uncaught Error: Call to a member function query() on null in /opt/zbox/app/zentao/lib/base/dao/dao.class.php:703

## 其他测试
1. `成功测试` 在服务器B上，创建一个新的容器 zentao-server-981，挂在在新的空目录上，添加一些测试数据，然后按照上面9~12的步骤，能正常升级到 12.0.1，测试数据都在

2. `失败测试` 可能由于版本跨度太大，从第10步 换成了  `Tag 10.6`，docker升级日志竟然只是普通的启动日志。
> ZBOX是Apache、Mysql、PHP的精简的集成环境。使用时，需要将其解压到/opt目录。
> /opt/zbox/zbox -h     可以获取帮助
> /opt/zbox/zbox start  启动脚本
> Mysql 用户名root，密码为123456。
> 更多可以访问http://www.zentao.net/goto.php?item=zbox.
> Start Apache success
> Start Mysql success
> 
版本还是 9.8.1 没有`The Zentao need update`这样开头升级日志。
该步骤尝试多次，升级到 9.8.3 也是如此，版本还是9.8.1。

**只有升级到 `11.7` or `12.0.1` 才有正常的升级日志**，但是访问 `upgrade.php` 都会出现文中一开始的错误 `Uncaught Error: Call to a member function query() on null`

## 结论
直接恢复原有镜像和业务数据，基于9.8.1版本能正常使用，升级版本后无法使用

基于以上情况，请问下如何解决？谢谢！

**Comment by idoop** [comment]
抱歉，镜像是在11.4.1的时候开始做升级策略的，在此之前，并未做升级功能。不过好在Dockerfile中已经包含upgrade.php，因此可以用逐步升级的方式，建议是拉区本仓库后，修改为之前10.x的禅道下载链接，构建一个10.x的禅道镜像升级后，再升到11.x，最后12.x。

**Comment by hostSugar** [comment]
不好意思，有2点不明白：
1. 10.x的镜像 docker hub上已经有了，为何需要通过仓库源码构建？
2. 大概流程清晰了，先升级到10.x，再后续一步步升级。但是我本地的9.8.1怎么升级到10.x呢？

**Comment by idoop** [comment]
@suan2046 通过导出数据的方式即可。
