### ISSUE TITLE
使用docker restart 命令之后zentao文件夹消失

### ISSUE THREAD

**Issue by Yampery** [idoop/zentao#35]
## 版本
**12.3**

## 问题描述
运行容器（zentao-server）之后，重启容器：`docker restart zentao-server`，系统会提示为了安全，删除zbox/app/zentao/www/upgrade.php，删除该文件后，再次重启禅道，访问禅道主页出现如下提示：

> You don't have permission to access /zentao/ on this server.

查看`zbox/app/`目录，发现`zentao`文件夹消失。

**Comment by liy05** [comment]
怎么解决的大佬，我也遇到这个问题
