### ISSUE TITLE
docker容器重启之后，报403错误

### ISSUE THREAD

**Issue by liy05** [idoop/zentao#36]
12.3版本docker容器重启之后，自动更新，删除了zentao文件夹，导致报错
![image](https://user-images.githubusercontent.com/35552675/86312532-84887980-bc55-11ea-9644-66170f288782.png)

**Comment by idoop** [comment]
@liy05 更新了下,你重新拉一下latest镜像.

**Comment by nwz5d** [comment]
我也是同样的问题，重新拉了之后还是不行啊
