### ISSUE TITLE
apache 2.4.48及以下有个SSRF漏洞，软件什么时候能更新下。

### ISSUE THREAD

**Issue by xmlbw** [idoop/zentao#42]
目前集成的apache版本是2.4.48，但这个版本及以下mod_proxy模块有个SSRF漏洞，软件什么时候更新下。

**Comment by idoop** [comment]
@xmlbw 这个镜像其实是对禅道官方的一键安装包的封装,这边能做的只是下载最新官方的一键安装包做成镜像,如果要升级apache版本,还是需要官方那边支持.因此若有升级apache需求的话,建议直接到官方论坛发帖,官方会给予回复的.
