### ISSUE TITLE
Host '119.184.127.215' is not allowed to connect to this MariaDB server.

### ISSUE THREAD

**Issue by DreamPWJ** [idoop/zentao#43]
无法连接

**Comment by idoop** [comment]
这些错误都是数据库的基操哦, 请善用搜索引擎,

**Comment by DreamPWJ** [comment]
@idoop  其他数据库连接是正常的，咱们这个数据库内嵌了，所以连接不正常

**Comment by DreamPWJ** [comment]
都已经搜索过了，关键是docker里面连mysql命令都不能执行
![image](https://user-images.githubusercontent.com/16730031/149469991-f64720b8-a145-494b-b82f-f42bea4f439a.png)

**Comment by idoop** [comment]
@DreamPWJ 为何一定要到容器中操作呢? 只要将容器内数据库的端口开放出来即可. 本仓库中的`docker-compose.yaml`示例里默认已将3306端口映射出来, 已可在当前网络内的任意主机上通过`mysql`命令或工具如`Navicat`或`MySQL Workbench`对此数据库操作.

**Comment by DreamPWJ** [comment]
我直接使用的启动的  sudo docker run -d --restart=always -p 8000:80 -p 3308:3306 --name zentao-server \
-e BIND_ADDRESS="false" -v /my/zentao:/opt/zbox  idoop/zentao:latest ，就是改了端口号而已

**Comment by DreamPWJ** [comment]
因为其他的数据库都连接正常，唯独zentao这个不行，应该是有兼容性问题@idoop

**Comment by DreamPWJ** [comment]
网上方法是很多  如 https://confluence.atlassian.com/jirakb/configuring-database-connection-results-in-error-host-xxxxxxx-is-not-allowed-to-connect-to-this-mysql-server-358908249.html  必须是先又mysql命令才能更改mysql主机绑定

**Comment by DreamPWJ** [comment]
JHost '119.184.127.215' is not allowed to connect to this MariaDB server

遗失对主机的连接。

**Comment by idoop** [comment]
@DreamPWJ 我懂你的意思了。按照你启动的命令来，在启动容器后，首先执行`docker exec -it zentao-server /bin/bash`进入容器，然后你可以使用`/opt/zbox/bin/mysql -h127.0.0.1 -uroot -p123456`执行连接, enjoy it.

**Comment by idoop** [comment]
连接后第一步还是`use mysql; update user set host = '%' where user = 'root';`不用就关闭3306的端口映射.

**Comment by DreamPWJ** [comment]
缺的是/opt/zbox/bin/mysql -h127.0.0.1 -uroot -p123456这条命令  谢了
