### ISSUE TITLE
10.3的版本号还是9.8

### ISSUE THREAD

**Issue by zhengmz** [idoop/zentao#5]
感谢你的分享。
使用你的docker image, idoop/zentao:10.3来升级
重新启动后，看到右下角还是9.8
不知我哪里操作有问题，谢谢。

**Comment by idoop** [comment]
你好，你是用的原来9.8版本的吗？如果是升级的话，需要解压源代码去覆盖，而不是用docker 镜像升级的，参考官方的升级指南。
