### ISSUE TITLE
官网上已经出10.5.1了，docker镜像什么时候更新，我本地是docker安装的10.3怎么升级？

### ISSUE THREAD

**Issue by jiangxianliang007** [idoop/zentao#6]
官网上已经出10.5.1了，docker镜像什么时候更新，我本地是docker安装的10.3怎么升级？

**Comment by idoop** [comment]
升级的话,使用最新镜像是无效的.下载最新的zentao代码,按照[官方指导](https://www.zentao.net/book/zentaopmshelp/67.html)覆盖你挂载出来的路径下,开源版的路径是 `$volume/app/zentao`.
