### ISSUE TITLE
容器启动的禅道, 隔一段时间再访问会跳转到upgrade.php

### ISSUE THREAD

**Issue by ityoung** [idoop/zentao#7]
原来一直访问正常, 今天访问的时候(`mydomain/zentao`), 自动跳转到`mydomain/zentao/upgrade.php`, 并且请求在这个路由循环.

![image](https://user-images.githubusercontent.com/12296804/50805456-6f1ae380-132d-11e9-92df-e39886186551.png)

之前出现过一次, 后来是把数据导出, 重建了容器才解决的. 但是希望能找到原因和解决办法, 感谢!

**Comment by idoop** [comment]
先试试把网络模式改为host模式在启动.

**Comment by ityoung** [comment]
我是用k8s启动的, 不是docker-compose... 奇怪的是为啥之前用的好好的, 突然会变成这样...

**Comment by ityoung** [comment]
k8s去掉中间的Nginx转发, 直接连接pod暴露的端口, 也是出现302跳转到upgrade.php...

**Comment by idoop** [comment]
直接试试在`Service`中指定网络为`NodePort`看是否为网络问题,或者你先用源码升级到最新版的试试.

**Comment by idoop** [comment]
如果你没有升级过,应该不存在`upgrade.php`这个文件,并且升级完毕后也应该会删除`upgrade.php`这个文件,除非升级没有完成就中断了.

**Comment by ityoung** [comment]
我试过你前面说的指定网络, 最后还是无效.

不过问题我解决了, 目前猜测, 可能就是你说的upgrade中断导致的.

解决方法:
1. 下载禅道源码, 复制`zentao/www`目录下的`upgrade.php`到我的环境中
2. 这时候再访问`upgrade.php`已经不会死循环了, 会有升级提示出现, 按提示执行完成即可
3. 修改原来K8s中的配置, 将禅道的版本从`latest`改为具体的版本, 例如"10.6", 防止以后又出现更新问题

这次出现这个问题是我原来切换集群时候迁移产生的, **感谢您的帮助**, 也希望有人遇到这个问题能够参考解决.
