### ISSUE TITLE
绑定钉钉群机器人Webhook通知，无法成功发送通知

### ISSUE THREAD

**Issue by zhangsean** [idoop/zentao#8]
我部署了idoop/zentao:latest（10.6.stable）版本，admin登录，后台，通知，Webhook，添加Webhook，类型选择钉钉，填写Webhook地址，保存。
任务变动后，在Webhook日志看到无法解析域名`oapi.dingtalk.com`，手工在/etc/hosts文件中添加相应的IP。随后任务变动后可以看到Webhook日志结果是0，但是钉钉群没有收到消息。
> 问题：
* 请版主试试配置钉钉群可以正常发送通知吗？
* 为什么这个容器不像其他容器一样继承主机的域名服务器从而自动解析域名呢？

**Comment by idoop** [comment]
@zhangsean 你好, 我这儿测试是OK的, 如果你是使用`docker-compose`起来的, 请试试添加并指定`dns`或`extar_host`字段的值.

**Comment by limengchang** [comment]
@zhangsean 最后解决了吗？我也遇到了此问题，同样的环境其他容器就能正常解析

**Comment by idoop** [comment]
@limengchang @zhangsean 请试一下最新的镜像,换了个基础镜像构建了.

**Comment by zhangsean** [comment]
我在本地测试可以正常发出钉钉通知了，等空闲时间在服务器上升级这个版本试一试！

**Comment by idoop** [comment]
@zhangsean 🆗,那我关闭这个Issue,如果还有问题你到时候再开.
